### ISSUE TITLE
Npm run build errors & app setup errors

### ISSUE THREAD

**Issue by stixcraven** [ngageoint/mage-server#74]
Hello
I am struggling to set up Mage i run the NPM run build and it returns this error:

```
> mage-server@5.3.4 build /opt/mage
> npm --prefix public install && npm --prefix public run build

npm ERR! code 128
npm ERR! Command failed: git submodule update -q --init --recursive
npm ERR! fatal: No url found for submodule path 'gh-pages' in .gitmodules
npm ERR! 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mage/.npm/_logs/2020-03-03T13_48_16_079Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mage-server@5.3.4 build: `npm --prefix public install && npm --prefix public run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mage-server@5.3.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/mage/.npm/_logs/2020-03-03T13_48_16_232Z-debug.log
```
I check the logs and it says the exact same thing. If I act like this has succeeded and go to run the server I am then hit with this error. I have followed the steps in #54 and use the Mage Cookie command before node app.js and this is the result: 
```
2020-03-03T13:55:43.791Z - error: error initializing database: Error: Cannot find module 'http-proxy-middleware'
Require stack:
- /opt/mage/plugins/mage-geoserver/index.js
- /opt/mage/plugins/index.js
- /opt/mage/app.js
```

I am then unable to access the local host url.

**Comment by danielbarela** [comment]
This is due to a change to a dependency of GeoPackage-JS.  I am working on a fix right now and will let you know when I have completed the fix.

**Comment by danielbarela** [comment]
Please try again, this should be fixed now.  The issue was that GeoPackage-JS was pointing to the repository for sql.js and that repository has since changed.  Modified GeoPackage-JS to point to the deployed version.

**Comment by stixcraven** [comment]
I have tried again and whilst I still have the same error as above (first block of code) I am now presented this error when I run MAGE_SESSION_COOKIE_SECURE=false node app.js:

`Error: Cannot find module '@ngageoint/geopackage'
Require stack:
- /opt/mage/utilities/geopackage.js
- /opt/mage/routes/layers.js
- /opt/mage/routes/index.js
- /opt/mage/express.js
- /opt/mage/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/opt/mage/utilities/geopackage.js:4:25)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at module.exports (/opt/mage/routes/layers.js:14:20)
    at /opt/mage/routes/index.js:54:26
    at Array.forEach (<anonymous>)
    at module.exports (/opt/mage/routes/index.js:51:29)
    at Object.<anonymous> (/opt/mage/express.js:84:20)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at require (internal/modules/cjs/helpers.js:77:18) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/opt/mage/utilities/geopackage.js',
    '/opt/mage/routes/layers.js',
    '/opt/mage/routes/index.js',
    '/opt/mage/express.js',
    '/opt/mage/app.js'
  ]
}
`

I have run a fresh clone from git before running this

**Comment by danielbarela** [comment]
Please try from master, and we will have a new release available, with the fix in it, in the near future.
